language: php

git:
  depth: 1

matrix:
  include:
    - php: 7.1
    - php: 7.2
      env:
      - LINT=true

  fast_finish: true

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - composer install -n

script:
  - vendor/bin/phpunit
  # Verify coding standard compliance only once
  - if [[ $LINT = true ]]; then
      composer cs-check;
    fi

notifications:
  email: false
